### ISSUE TITLE
Trouble with firmware read

### ISSUE THREAD

**Issue by reimerp** [intx82/fx2-i2c-tiny-usb#2]
Hi, maybe you can help or give some hints.

I build the firmware successful and uploaded to fx2. Devive is detected with lsusb.
I made some test with riny rtc which was working successful on rpi1 i2c port. I tried same get / dump commands unforzunately unsuccessful on my fx2 which were working on the pi. So I think the rtc device is working. fx2 seems ok as well.
 icdetect is showing both addresses (it containd a DS1307 on 0x67 and a 24C32 on 0x50) with lots of dmesg errors,
"2c i2c-7: failure reading data" or "i2c i2c-7: failure reading status". Ignoring this an i2cget on the DS1307 or an  i2cdump on the eeprom is just reading 0xff. No errors in dmesg but read values are wrong.
What might be the readon of this?

**Comment by intx82** [comment]
first, share please the dmesg errors. Then, add 4.7k resistors between SDA/VCC and SCL/VCC. Also, you may try to decrease i2c speed to 100khz or even less.

**Comment by reimerp** [comment]
I added Pullups. (10k for 5V, 4k7 for 3.3V) devices ) and made test witch a couple of devices, mostly 24x eeproms but also a DS1307 which  also contains a 24 eeprom. If I do a `i2cdetect -y` on the bus, I get lots of same errors, but when I narrow it to just one device (eg 0x50) with `i2cdetect -y 10 0x50 0x50` just a single error is reported in dmesg:
` i2c i2c-10: failure reading data`
-- when I change the address to 0x20 (no device there) dmes changes to 
`i2c i2c-10: failure reading status`.
i2cdetectt does not detect a device in any case.
Meanwhile I programmed i2ctiny on my digispark and its working fine -- with external pullups on an OC bus -- or with internal pullups. I don't know how to decrease speed (except putting some delay in code) and the docs reads its should kust be 70k due to bitbanging.   Maybe I will change the code to make use of the fx2 internal I2C bus ( and skip messing up with the internal eeprom like smbusb does -- but this does not provide kernel drivers and therefor no /dev/i2c interface.

**Comment by reimerp** [comment]
Even w/o anyting on the bus these dmesg issues are preset, whether there are pulluos or not.

Maybe there is a versioning / dependancy issue the cause of it.

A fresh checkout compiles on sdcc 4.1.0. with sdcc 4.5.0 you get:
```
sdar rc lib/huge/fx2dfu.lib build/huge/usbdfu.rel
sdcc -mmcs51 --std-sdcc99 -Iinclude  --model-huge -c -o build/huge/uf2scsi.rel uf2scsi.c
sdcc -mmcs51 --std-sdcc99 -Iinclude  --model-huge -c -o build/huge/uf2fat.rel uf2fat.c
uf2fat.c:54: warning 291: enumeration constant outside the range of int requires ISO C23 or later
sdar rc lib/huge/fx2uf2.lib build/huge/uf2scsi.rel build/huge/uf2fat.rel
make[1]: Verzeichnis „/home/prochnor/examples/mcs51/ic2_test/libfx2/firmware/library“ wird verlassen
make[1]: Verzeichnis „/home/prochnor/examples/mcs51/ic2_test/libfx2/firmware/boot-cypress“ wird betreten
sdcc -mmcs51 --iram-size 0x100 --code-size 0x3e00 --xram-loc  0x3e00 --xram-size 0x0200 --std-sdcc99 --model-small  -I../library/include -L../library/lib/small -Wp,-MQ,build/main.rel,-MMD,build/main.d -c -o build/main.rel main.c
sdcpp: warning: '-x c' after last input file has no effect
cc1: fatal error: build/main.d: No such file or directory
compilation terminated.
at 1: warning 190: ISO C forbids an empty translation unit
subprocess error 256
make[1]: *** [../library/fx2rules.mk:39: build/main.rel] Fehler 1
```

Remark: yes this deletes src/main.c....

Since this is caused ny librarys version I updated:
`git submodule update --remote`
but the lib fails building the code now, since deprecattion of biffers:
```
main.c:144: error 20: Undefined identifier 'SETUP_EP0_BUF_is_deprecated_use_SETUP_EP0_IN_BUF_or_SETUP_EP0_OUT_BUF_instead'
```

You can find latest versions that accepts old buffer definitions with
`cd libfx2 && git checkout 748c2564aef` 

this version compiles in sdcc 4.5 but error still exsts. Also no devices found.

**Comment by intx82** [comment]
Try now
